### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Sir-Udo** [ndg63276/smartlife#13]
Hi,

for a few weeks now, every time I restart HA, I've been asked to re-authenticate myself in Smartlife. Can this be fixed?
I heard it was similar at TUYA, they probably fixed it at Tuya. Thanks Udo

**Comment by ndg63276** [comment]
This code just sends your credentials to Smartlife, and stores the token they send back as a cookie. If Smartlife says the token is no longer valid, there's nothing I can do about that, apart from asking you to re-authenticate.

If you see any useful messages in the dev console, let me know.

**Comment by Sir-Udo** [comment]
Recently, every time I restart Home Assistant, I have to re-authenticate myself with the app in Smartlive.
I think it's the same problem Tuya had recently. Can you please see if you can fix something?


Protokolldetails (FEHLER)
Logger: homeassistant.config_entries
Quelle: config_entries.py:586
Erstmals aufgetreten: 08:21:15 (1 Vorkommnisse)
Zuletzt protokolliert: 08:21:15

Error setting up entry XXX@XXX.de for smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 69, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.report_version, __version__, smart_life_version, sharing_sdk)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/manager.py", line 69, in report_version
    self.user_repository.user_version_report(ha_version, integration_version, sdk_version)
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/user.py", line 46, in user_version_report
    self.api.post("/v1.0/m/life/home-assistant/qrcode/versions", None, {
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid
